server:
  port: 8140 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-vod # 服务名

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址

aliyun:
  vod:
#    endpoint: oss-cn-shenzhen.aliyuncs.com
    keyId: LTAI5tB1hMFcsxip54YJbEiz
    keySecret: 6MoX5olwNOtMjQTjLTsgyUId80Ia3R
#    bucketName: kel-file-kimi